version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    container_name: database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - dba:/var/lib/postgresql/data
    networks:
      - back-kanban

  backend:
    image: node:18
    container_name: backend
    working_dir: /home/backend
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - .:/home/backend
    ports:
      - '5000:5000'
    networks:
      - back-kanban
    depends_on:
      - database
    command: bash -c "npm i && npm run build && npm run migration:push && npm run start"

networks:
  back-kanban:
    driver: bridge
volumes:
  dba:
    driver: local
